### ISSUE TITLE
Editing the chromosome list?

### ISSUE THREAD

**Issue by kmegq** [epigen/LIQUORICE#1]
Hello,
I have a question regarding using LIQUORICE on non-human samples. Can the list of chromosomes allowed be edited? I'm working with dog samples, so want to include chr1-38 + X.
Thank you for your help!
Best,
Kate

**Comment by peneder** [comment]
Hi Kate,
Thanks for your interest in the tool, and sorry for the super late reply - I thought I had notifications on, but apparently I didn't. Would this still be useful for you? If yes, I could easily implement that.
Best
Peter

**Comment by peneder** [comment]
I'm closing the issue for now, but feel free to re-open if this is still relevant for you, then I could still implement your request.
