### ISSUE TITLE
Example Misleading

### ISSUE THREAD

**Issue by sashamain** [epigen/LIQUORICE#2]
Hi there,

Thank you for creating this fantastic tool. I just wanted to let you know that your example at the end of https://liquorice.readthedocs.io/en/latest/liquorice_commandline_tool.html could be misleading for novices (like myself). It's not clear that users need to remove the quotes around $SAMPLE at the start of the for loop. Just a suggestion to make it clearer. :)

**Comment by peneder** [comment]
Hi Sasha, 
Sorry for the late reply and the mistake in the example, hope you didn't struggle for too long! I now fixed the error in the docs, thanks a lot for letting me know! :)
