### ISSUE TITLE
LIQUORICE_summary not recognized and showing the same help message as LIQUORICE

### ISSUE THREAD

**Issue by LuoPangpang** [epigen/LIQUORICE#3]
Hello! I managed to run the first step (LIQUORICE) as shown in the test_LIQUORICE_with_simple_testdata.sh and generated a directory named 'Ctrl_17_testdata'. Then I tried to run LIQUORICE_summary but the command did not seem to be recognized (or wrongly recognized as LIQUORICE?) as it pop out the help message of LIQUORICE. 

![image](https://github.com/epigen/LIQUORICE/assets/39048164/0bc1ebf6-0bd3-4567-a653-c2e4df166f6b)

Then I tried to look at what was inside LIQUORICE_summary and the result is captured as follow. I have compared it with what was inside LIQUORICE and I couldn't find anything wrong.

![image](https://github.com/epigen/LIQUORICE/assets/39048164/e8ace82e-0250-4376-86e6-d9c75f2fac47)

Any thoughts would be appreciated.

**Comment by peneder** [comment]
Hi, thanks for your interest in our tool! :)

I just checked on a fresh install of LIQUORICE ("mamba  create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core"), and for me LIQUORICE_summary behaves as expected - it gives the following message when called with "LIQUORICE_summary --help":

usage: LIQUORICE_summary [-h] [--dirname DIRNAME]
                         [--control_name_list CONTROL_NAME_LIST [CONTROL_NAME_LIST ...]]
                         [--binsize BINSIZE] [--extend_to EXTEND_TO]
                         [--smooth_sigma SMOOTH_SIGMA]
                         [--use_uncorrected_coverage]
                         [--these_regionsets_only THESE_REGIONSETS_ONLY [THESE_REGIONSETS_ONLY ...]]
                         [--prediction_interval_alpha PREDICTION_INTERVAL_ALPHA]

[...]

Could you let me know exactly how you installed LIQUORICE? Maybe also try with a fresh install in a new environment, and maybe try using mamba instead of conda (https://mamba.readthedocs.io/en/latest/installation.html). The current version of LIQUORICE is 0.5.6, so make sure you have that installed.

Also, it might be useful to type "which LIQUORICE_summary" and "which LIQUORICE" - for me, they are located under <path to my conda installation>/envs/LIQUORICE/bin/LIQUORICE_summary and <path to my conda installation>/envs/LIQUORICE/bin/LIQUORICE.

best
Peter

**Comment by LuoPangpang** [comment]
Hi Peter,

The "conda create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core" stuck for 12 hours at solving environment, so I git clone the code and use "python setup.py install" to do the installation. The first step LIQUORICE runs without error. As shown above the "which LIQUORICE_summary" and "which LIQUORICE" are located at the same */bin directory.

For the second step LIQUORICE_summary, I found a workaround by using the docker instead. Could you provide some instructions on using the LIQUORICE docker image? Thank you!

Kind Regards,

Luo

**Comment by peneder** [comment]
Hi Luo,

I see! I need to look into the issue with conda (for me conda also gets stuck solving the environment, while that doesn't happen when I use mamba instead).

The docker image should be a good workaround, yes! It's pretty straightforward to use - the image is just a linux image with liquorice installed via mamba. So all you need to do is navigate to the directory that contains your LIQUORICE result files, and then run:

docker pull peneder/liquorice

and then:

docker run -v $(pwd):$(pwd) -w $(pwd) peneder/liquorice LIQUORICE_summary < add command line arguments here>

(the -v option mounts your current working directory under the same path in the docker container)
(the -w option sets the working directory of the container to the path of your current working directory)

Hope that helps, let me know if it works for you!

best
Peter

**Comment by LuoPangpang** [comment]
Hi Peter,

Here is the log when I tried to run the docker command:

>docker run -v $PWD:/some_dir_in_container --workdir /some_dir_in_container peneder/liquorice LIQUORICE_summary
Traceback (most recent call last):
  File "/opt/conda/bin/LIQUORICE_summary", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 841, in main
    summary_df = create_summary_table_LIQUORICE(dirname=dirname, control_name_list=control_name_list,
  File "/opt/conda/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 680, in create_summary_table_LIQUORICE
    "Dip area: z-score vs controls in same region set": summary_df.apply(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/apply.py", line 271, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/apply.py", line 300, in apply_series_generator
    results[i] = self.f(v)
  File "/opt/conda/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 681, in <lambda>
    lambda x: zscore_to_control(x, control_summary_df, "Total dip area (AOC combined model)"), axis=1),
  File "/opt/conda/lib/python3.8/site-packages/liquorice/LIQUORICE_summary.py", line 205, in zscore_to_control
    return round((row[col] - mean_ctrl) / std_ctrl, 2)
numpy.core._exceptions.UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U1053'), dtype('float64')) -> None

where $PWD contains the output directory of LIQUORICE for several samples. Below is the content of fitted_gaussians_parameter_summary.csv in one of the samples:

>cat control-01.bqsr/universal_DHSs/fitted_gaussians_parameter_summary.csv
G1_amplitude,G1_sigma,G2_amplitude,G2_sigma,G3_amplitude,G3_sigma,Bayesian Information Criterion,Total dip depth,Intercept,Total dip area (AOC combined model),sample,region-set
-148.18784142497228,149.99957249018598,33.15616942597844,757.9661258083537,-456.9149504084487,6078.670604812409,-587.5879528500124,0.4066598690544208,0.01549891618119405,"[   -45.43244326    -55.33752107    -66.94758782    -80.44735927
    -96.01747424   -113.8283363    -134.03311928   -156.76008387
   -182.10441509   -210.11985348   -240.81044991   -274.12282239
   -309.93932732   -348.0725728    -388.26169524   -430.17078829
   -473.38981519   -517.4382513    -561.77159599   -605.79076577
   -648.85423923   -690.2926402    -729.42410459   -765.54538523
   -797.60927829   -821.72220045   -821.43111051   -755.97459154
   -594.82340712  -1533.41642868 -10934.19442629 -11457.36059865
 -12057.46452512 -11457.36059865 -10934.19442629  -1533.41642868
   -594.82340712   -755.97459154   -821.43111051   -821.72220045
   -797.60927829   -765.54538523   -729.42410459   -690.2926402
   -648.85423923   -605.79076577   -561.77159599   -517.4382513
   -473.38981519   -430.17078829   -388.26169524   -348.0725728
   -309.93932732   -274.12282239   -240.81044991   -210.11985348
   -182.10441509   -156.76008387   -134.03311928   -113.8283363
    -96.01747424    -80.44735927    -66.94758782    -55.33752107
    -45.43244326]",control-01.bqsr,universal_DHSs

Did I miss some parameters in the LIQUORICE_summary step? Thank you!

Best
Luo

**Comment by peneder** [comment]
Hi Luo,

that's odd - the fitted_gaussians_parameter_summary.csv file has a weird entry for the "Total dip area (AOC combined model)" , it's a list in quotation marks, whereas it should just be a normal, single floating point value. 

Here's an example of what this file should look like:

G1_amplitude,G1_sigma,G2_amplitude,G2_sigma,G3_amplitude,G3_sigma,Bayesian Information Criterion,Total dip depth,Intercept,Total dip area (AOC combined model),sample,region-set
-183.99003667981896,149.99999999631817,47.315744285837184,757.999998780965,-307.1227755461749,6078.968403592619,-685.2813836669626,0.4845954530699526,0.00957071963804905,-471.83485590386266,CTR_010_01_01_EM_S115256_reheadered,Universal_DHSs

I'm thinking this might be related to the way your LIQUORICE was installed, or some dependency having the wrong version. Could you maybe try to re-run LIQUORICE in the docker version  (i.e. use the docker image both for LIQUORICE and LIQUORICE_summary, in a new output folder)? 

Hope that helps, sorry for the hassle!
best
Peter

**Comment by LuoPangpang** [comment]
Hi Peter,

I am glad to tell you that running LIQUORICE and LIQUORICE_summary within a mamba installed environment or a docker runs perfectly well! Thank you very much! 

Best,
Luo

**Comment by peneder** [comment]
Ok great, glad this worked!

All the best
Peter
