### ISSUE TITLE
Cannot be installed via conda or mamba

### ISSUE THREAD

**Issue by DucoG** [epigen/LIQUORICE#4]
`mamba create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core`

error:

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
├─ liquorice is not installable because it requires
│  └─ biopython 1.79 , which conflicts with any installable versions previously reported;
└─ ray-core is not installable because there are no viable options
   ├─ ray-core [1.0.1|1.1.0|...|1.9.2] would require
   │  └─ grpcio >=1.28.1  but there are no viable options
   │     ├─ grpcio 1.30.0 would require
   │     │  └─ c-ares >=1.15.0,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.31.0|1.32.0|1.33.1|1.33.2] would require
   │     │  └─ c-ares >=1.16.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.34.0|1.34.1|...|1.38.1] would require
   │     │  └─ c-ares >=1.17.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.39.0|1.40.0|1.41.0|1.41.1] would require
   │     │  └─ c-ares >=1.17.2,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.41.1|1.42.0|...|1.54.2] would require
   │     │  ├─ c-ares >=1.18.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     │  └─ libgrpc [1.51.1 hbc085c6_2|1.51.1 hcf146ea_3|...|1.54.2 hcf146ea_0], which requires
   │     │     └─ c-ares >=1.18.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.54.3|1.55.0|...|1.57.0] would require
   │     │  └─ libgrpc [1.54.3 hb20ce57_0|1.55.0 h59456c1_0|...|1.57.0 ha4d0f93_1], which requires
   │     │     └─ c-ares >=1.19.1,<2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ grpcio 1.31.0 conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.35.0|1.36.0|1.36.1] conflicts with any installable versions previously reported;
   │     ├─ grpcio 1.42.0 conflicts with any installable versions previously reported;
   │     └─ grpcio 1.48.2 conflicts with any installable versions previously reported;
   ├─ ray-core [1.11.0|1.11.1|...|2.0.0] would require
   │  └─ grpcio [>=1.28.1,<1.48 |>=1.28.1,<=1.43.0 |>=1.28.1,<=1.46.0 ] but there are no viable options
   │     ├─ grpcio 1.30.0, which cannot be installed (as previously explained);
   │     ├─ grpcio [1.31.0|1.32.0|1.33.1|1.33.2], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.34.0|1.34.1|...|1.38.1], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.39.0|1.40.0|1.41.0|1.41.1], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.41.1|1.42.0|...|1.54.2], which cannot be installed (as previously explained);
   │     ├─ grpcio 1.31.0 conflicts with any installable versions previously reported;
   │     ├─ grpcio [1.35.0|1.36.0|1.36.1] conflicts with any installable versions previously reported;
   │     └─ grpcio 1.42.0 conflicts with any installable versions previously reported;
   ├─ ray-core 2.0.1 would require
   │  └─ grpcio >=1.32.0,<1.48  but there are no viable options
   │     ├─ grpcio [1.31.0|1.32.0|1.33.1|1.33.2], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.34.0|1.34.1|...|1.38.1], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.39.0|1.40.0|1.41.0|1.41.1], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.41.1|1.42.0|...|1.54.2], which cannot be installed (as previously explained);
   │     ├─ grpcio [1.35.0|1.36.0|1.36.1] conflicts with any installable versions previously reported;
   │     └─ grpcio 1.42.0 conflicts with any installable versions previously reported;
   ├─ ray-core [2.1.0|2.2.0|...|2.6.3] would require
   │  └─ grpcio >=1.42,<1.49  but there are no viable options
   │     ├─ grpcio [1.41.1|1.42.0|...|1.54.2], which cannot be installed (as previously explained);
   │     ├─ grpcio 1.42.0 conflicts with any installable versions previously reported;
   │     └─ grpcio 1.48.2 conflicts with any installable versions previously reported;
   └─ ray-core [1.4.0|1.6.0|1.9.2|2.0.1|2.3.0] conflicts with any installable versions previously reported.
```

**Comment by DucoG** [comment]
update: got the tool working by manually installing required packages using pip. However the summary tool is not working.

**Comment by peneder** [comment]
Hi!
Sorry for the troubles with the installation and the late reply, I was on holidays. I'll look into this now!

I think maybe not everything is installed with the correct version via pip, and this leads to downstream problems with the summary tool. In the meantime (while I try to fix the conda/mamba install), you could try to use the docker image, like so:

`docker pull peneder/liquorice`

and then:

`docker run -v $(pwd):$(pwd) -w $(pwd) peneder/liquorice LIQUORICE < add command line arguments here>`
`docker run -v $(pwd):$(pwd) -w $(pwd) peneder/liquorice LIQUORICE_summary < add command line arguments here>`

(the -v option mounts your current working directory under the same path in the docker container)
(the -w option sets the working directory of the container to the path of your current working directory)

In this case, you would need to use the docker version both for LIQUORICE and for LIQUORICE_summary. Running the docker-version LIQUORICE_summary on the pip-version LIQUORICE output probably won't work.

best 
Peter

**Comment by peneder** [comment]
Hi again,

It seems that the installation issue has to do with "strict channel priority".
I used the condaforge/mambaforge docker container to start out with a fresh copy of mamba. When I run `mamba create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core`, the installation works fine. However, when I run `mamba create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core --strict-channel-priority`, I can reproduce your issue. I guess you have specified strict channel priority somewhere in your conda or mamba configuration.

One workaround seems to be to change the order in which the channels are specified, i.e. use 
`mamba create -n LIQUORICE -c conda-forge -c bioconda liquorice ray-core --strict-channel-priority` instead of `mamba create -n LIQUORICE -c bioconda -c conda-forge liquorice ray-core --strict-channel-priority`.

Can you let me know if `mamba create -n LIQUORICE -c conda-forge -c bioconda liquorice ray-core ` works for you?

Best
Peter

**Comment by DucoG** [comment]
Hi Peter,

I was unaware but i did have strict channel priority on, which I set to flexible. 

now `mamba create -n LIQUORICE -c conda-forge -c bioconda liquorice ray-core` does resolve, thanks! :)

#5 probably caused by environment issues. I'll close that issue if this resolves that issue as well.
