### ISSUE TITLE
LIQUORICE_summary can't recognize liquorice output

### ISSUE THREAD

**Issue by imdanique** [epigen/LIQUORICE#7]
I have all the output files of LIQUORICE in my directory, however `LIQUORICE_summary` can't recognize it and throws an error:
```Could not find any 'fitted_gaussians_parameter_summary.csv' files in this directory. Exiting```
The file is located in the directory 
I tried both conda and docker version, gives the same error

**Comment by peneder** [comment]
Hi,
Thanks for your interest in using LIQUORICE :)
Could you please provide the commands you used to run LIQUORICE and LIQUORICE_summary? 

In case you didn't specify `--use_uncorrected_coverage`, LIQUORICE_summary will look for the files under `<dirname>/*/*/fitted_gaussians_parameter_summary.csv` and `<dirname>/*/fitted_gaussians_parameter_summary.csv`, where `<dirname>` is what you specify via `--dirname` (or the current working directory by default)

Could you please verify that the files are there, with:
```
cd <dirname>
ls */*/fitted_gaussians_parameter_summary.csv
ls */fitted_gaussians_parameter_summary.csv
```
In case you specified `--these_regionsets_only `, this could also be a possible cause for the tool not finding anything (it runs the following lines:
```
    if these_regionsets_only:
        param_summaries = [x for x in param_summaries if x.split("/")[-2] in these_regionsets_only]
```
)

best
Peter

**Comment by imdanique** [comment]
Hi @peneder,
Thank you very much for your reply, it solved my problem. The issue was that I ran `LIQUORICE_summary` in `dir/sample/universal_DHSs directory`, while I should've run it in `dir`
