### ISSUE TITLE
Huge (unrealistic) RAM requirement for a small region of interest BED file?

### ISSUE THREAD

**Issue by danarte** [epigen/LIQUORICE#8]
Hello,
Thank you for this great tool, I'm trying to use it with a region of interest file (15mb BED file) that I got from here:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129646
Specifically this file:
GSE129646_MDAMB231_Par_BrM_LM_atac.splitbysummit.bed.gz

I'm using it with on a small BAM aligned to the hg38 reference that is similar to the reference in the example.

For some reason it takes upwards of 300GB RAM to run liquorice with 12 processes, which is kind of absurd.

Could you help me understand if there is a problem and maybe how to fix it?

Here is the command I run:
LIQUORICE --bamfile bam_GRch38/RA_383B.bam --refgenome_fasta hg38_liq_reference/hg38.p12.fa --mappability_bigwig hg38_liq_reference/hg38.p12.fa_150bp.bw --bedpathlist  hg38_liq_reference/GSE129646_MDAMB231_Par_BrM_LM_atac.splitbysummit.fixed_chr.bed --samplename liqourice_output/RA_383B --blacklist hg38_liq_reference/hg38-blacklist.v2.bed --n_cpus 12 --extend_to 15000

**Comment by peneder** [comment]
Hi!
Thanks for your interest in the tool :)
300 Gb is indeed a bit much 😆  A few things to note here:
- The bed file you are using is quite large, with over 330k entries. Usually I've been running on sets that contains a few thousand regions only. If possible, I would start by subsetting this to e.g. the most important 10k regions.
- Potentially, the multiprocessing is making things worse here (not sure). You could try to run it on a singe process to see if that helps. If that improves things by so much that you have enough RAM for multiple runs in parallel, you could instead parallelize at the sample level (see https://liquorice.readthedocs.io/en/latest/liquorice_commandline_tool.html#parallelization).
- The bedfile you are using uses a notation with chromosome names like 1,2,3 etc. In this case, you need to specificy the "--no_chr_prefix" flag to get proper results - not sure if this helps for the RAM problem, though.
- You could also try "--speed_mode" to see if that helps with RAM usage. That simplifies the bias correction procedure (may be a little less accurate though)
- Finally, you could also try to increase --binsize and decrease --extend_to.

Hope that helps, just let me know if you need further help :)

**Comment by danarte** [comment]
Yes that definitely helps, thanks for the quick reply and multiple solutions, I'll try those.
Cheers!
